"use strict";
const assert=require("node:assert/strict"),test=require("node:test"),{EventEmitter}=require("node:events"),fs=require("node:fs"),os=require("node:os"),path=require("node:path");
const {createCodexSpecialistAgent}=require("../services/delegation/codex-specialist-agent");
const hasPrivacyLeak=(value)=>Object.values(value||{}).some((item)=>typeof item==="string"&&(/\/[A-Za-z0-9._-]+(?:\/[^\s]+)+:/.test(item)||/^\/(?:Users|home|opt|usr)\//.test(item)));
function task(root,id="run"){return {taskId:id,repositoryRoot:root,objective:"x",allowedPaths:[path.join(root,"src")],forbiddenPaths:[],constraints:[],maxIterations:1,maxDuration:1000};}
function child(code,signal){const c=new EventEmitter();c.stdout=new EventEmitter();c.stderr=new EventEmitter();c.killed=false;c.kill=()=>{};queueMicrotask(()=>c.emit("close",code,signal));return c;}
async function run(probe,code=0,signal=null,identity={sessionId:"session-test-a",runId:"run-test-a",taskId:"normalize-email",participant:"CODEX"}){const root=fs.mkdtempSync(path.join(os.tmpdir(),"noon-b19e-"));fs.mkdirSync(path.join(root,"src"));const events=[];let spawns=0;const agent=createCodexSpecialistAgent({versionProvider:()=>probe,spawnProcess:()=>{spawns++;return child(code,signal);},observability:(e,d)=>events.push([e,d])});const result=await agent.executeTask(task(root,identity.runId),{preflight:{agentsFiles:[]},benchmarkExecution:identity});return {events,spawns,result};}
for(const status of ["EXECUTABLE_NOT_FOUND","VERSION_COMMAND_FAILED","VERSION_EMPTY","VERSION_PARSE_FAILED"])test(`${status} bloque spawn`,async()=>{const x=await run({status,version:null});assert.equal(x.spawns,0);assert.equal(x.result.backend.invoked,false);assert.equal(x.result.backend.preSpawnFailure,status);assert.equal(x.events.some(([e])=>e==="codex_spawn_attempt"),false);assert.equal(x.events.find(([e])=>e==="codex_version_probe")[1].result,status);});
test("matrice spawn ordre corrélation et sorties",async()=>{for(const [code,signal] of [[0,null],[1,null],[null,"SIGTERM"]]){const x=await run({status:"VERSION_OK",version:"codex-cli 1"},code,signal);assert.equal(x.spawns,1);assert.equal(x.result.backend.invoked,true);assert.deepEqual(x.events.map(([e])=>e),["codex_cli_resolution","codex_version_probe","codex_spawn_attempt","codex_spawn_result"]);const last=x.events.at(-1)[1];assert.equal(last.childCreated,true);assert.equal(last.exitCode,code);assert.equal(last.signal,signal);for(const [,d]of x.events)assert.deepEqual([d.sessionId,d.runId,d.taskId,d.participant],["session-test-a","run-test-a","normalize-email","CODEX"]);assert.equal(x.events[0][1].source,"PATH");assert.equal(hasPrivacyLeak({source:"PATH"}),false);assert.equal(hasPrivacyLeak({value:"/usr/local/bin:/usr/bin:/bin"}),true);assert.equal(JSON.stringify(x.events).match(/HOME|secret|token|prompt/i),null);}});
test("identités A et B ne se mélangent pas",async()=>{const a=await run({status:"VERSION_OK",version:"codex-cli 1"},0,null,{sessionId:"A",runId:"A",taskId:"normalize-email",participant:"CODEX"}),b=await run({status:"VERSION_OK",version:"codex-cli 1"},0,null,{sessionId:"B",runId:"B",taskId:"normalize-email",participant:"CODEX"});assert.equal(JSON.stringify(a.events).includes('"B"'),false);assert.equal(JSON.stringify(b.events).includes('"A"'),false);});
