"use strict";
const test = require("node:test"); const assert = require("node:assert/strict");
const fs = require("node:fs"); const os = require("node:os"); const path = require("node:path");
const { buildCreativeBriefPrompt, createCreativeBriefStore, isDueToday, localDateKey, nextRunAt } = require("../lib/creative-brief");
test("programme 7 h avant et après l’heure prévue", () => { const before = new Date("2026-01-15T05:00:00Z"); assert.equal(nextRunAt({ now: before }).toISOString(), "2026-01-15T06:00:00.000Z"); const after = new Date("2026-01-15T07:00:00Z"); assert.equal(nextRunAt({ now: after }).toISOString(), "2026-01-16T06:00:00.000Z"); });
test("respecte les changements d’heure de Paris", () => { assert.equal(nextRunAt({ now: new Date("2026-07-15T04:00:00Z") }).toISOString(), "2026-07-15T05:00:00.000Z"); assert.equal(nextRunAt({ now: new Date("2026-01-15T04:00:00Z") }).toISOString(), "2026-01-15T06:00:00.000Z"); });
test("rattrape un brief manqué une seule fois", () => { const now = new Date("2026-01-15T09:00:00Z"); assert.equal(isDueToday({ now }), true); assert.equal(isDueToday({ now, lastSuccessDate: localDateKey(now) }), false); });
test("isole le prompt éditorial et rappelle les sujets récents", () => { const prompt = buildCreativeBriefPrompt({ date: "2026-08-24", recentTopics: [{ date: "2026-08-23", theme: "branding", title: "Une identité", url: "https://example.com", summary: "Déjà traité" }] }); assert.match(prompt.system, /cinq minutes/); assert.match(prompt.system, /À retenir aujourd’hui/); assert.match(prompt.user, /24 à 72 heures/); assert.match(prompt.user, /Une identité/); });
test("persiste la prochaine planification sans masquer un brief prêt du jour", () => { const root = fs.mkdtempSync(path.join(os.tmpdir(), "noon-brief-")); const store = createCreativeBriefStore(path.join(root, "brief.json")); const today = localDateKey(); store.markScheduled(new Date("2026-08-25T06:00:00Z")); assert.equal(store.load().status, "scheduled"); store.markReady({ date: today, topics: [] }); store.markScheduled(new Date("2026-08-26T06:00:00Z")); assert.equal(store.load().status, "ready"); assert.equal(store.load().nextScheduledAt, "2026-08-26T06:00:00.000Z"); });
