"use strict";

const test = require("node:test");
const assert = require("node:assert/strict");
const fs = require("node:fs");
const os = require("node:os");
const path = require("node:path");
const { createSkillRegistry } = require("../skills/registry");
const { createExtensionLoader, createExtensionRegistry, createExtensionRuntime, createExtensionStorage, defineExtension, validateManifest } = require("../services/extensions");

const object = (properties = {}, required = []) => ({ type: "object", additionalProperties: false, properties, required });
function manifest(overrides = {}) {
  const id = overrides.id || "com.test.readonly";
  return { id, name: "Test", version: "1.0.0", apiVersion: "1", type: "SKILL", entrypoint: "./index.js", capabilities: ["test.read"], permissions: ["READ"], supportedPlatforms: ["darwin"], minimumNoonVersion: "1.0.0",
    skills: [{ id: `${id}.read`, description: "Lecture", permissionLevel: "READ", inputSchema: object({ query: { type: "string" } }, ["query"]), outputSchema: object({ value: { type: "string" } }, ["value"]), timeoutMs: 100 }], ...overrides };
}
function moduleFor(rawManifest, handler = async ({ query }) => ({ value: query })) { return defineExtension({ manifest: rawManifest, activate: () => ({ skills: { [rawManifest.skills[0].id]: handler } }), healthCheck: async () => ({ ok: true }) }); }
function policy(outcome = "ALLOW") { return { createActionRequest: (request) => ({ ...request, actionFingerprint: "fp" }), evaluate: () => ({ outcome, decisionId: "decision-1" }) }; }
function fixture({ rawManifest = manifest(), handler, outcome = "ALLOW", developerMode = false, transactionalExecutor = null, storage, allowedRoots = [] } = {}) {
  const skills = createSkillRegistry([]); const runtime = createExtensionRuntime({ securityPolicy: policy(outcome), transactionalExecutor, storage, allowedRoots });
  const registry = createExtensionRegistry({ noonVersion: "1.0.6", skillRegistry: skills, runtime, developerMode }); runtime.bindRegistry(registry);
  const extension = moduleFor(rawManifest, handler); return { skills, runtime, registry, extension, rawManifest };
}
async function ready(options = {}) { const fx = fixture(options); fx.registry.discover({ manifest: fx.rawManifest, module: fx.extension, provenance: "BUNDLED", trust: "TRUSTED", signed: true }); fx.registry.install(fx.rawManifest.id, { approvedPermissions: fx.rawManifest.permissions }); await fx.registry.enable(fx.rawManifest.id); return fx; }

test("un manifest valide est normalisé", () => assert.equal(validateManifest(manifest()).compatibility, "COMPATIBLE"));
test("un manifest invalide est refusé", () => assert.throws(() => validateManifest({}), { code: "EXTENSION_MANIFEST_INVALID" }));
test("un champ inconnu est refusé", () => assert.throws(() => validateManifest({ ...manifest(), surprise: true }), { code: "EXTENSION_MANIFEST_UNKNOWN_FIELD" }));
test("une API incompatible n'est pas installable", () => { const fx = fixture({ rawManifest: manifest({ apiVersion: "2" }) }); const state = fx.registry.discover({ manifest: fx.rawManifest, module: fx.extension, provenance: "BUNDLED" }); assert.equal(state.state, "INCOMPATIBLE"); assert.throws(() => fx.registry.install(fx.rawManifest.id), { code: "EXTENSION_INSTALL_BLOCKED" }); });
test("une version Noon minimale est contrôlée", () => { const fx = fixture({ rawManifest: manifest({ minimumNoonVersion: "9.0.0" }) }); assert.equal(fx.registry.discover({ manifest: fx.rawManifest, module: fx.extension, provenance: "BUNDLED" }).state, "INCOMPATIBLE"); });
test("un ID d'extension dupliqué est refusé", () => { const fx = fixture(); fx.registry.discover({ manifest: fx.rawManifest, module: fx.extension, provenance: "BUNDLED" }); assert.throws(() => fx.registry.discover({ manifest: fx.rawManifest, module: fx.extension, provenance: "BUNDLED" }), { code: "EXTENSION_DUPLICATE_ID" }); });
test("une skill d'extension ne remplace pas une skill core", () => { const skills = createSkillRegistry([{ definition: { type: "function", name: "com.test.readonly.read", description: "core", strict: true, parameters: object() }, permissions: { level: "read" }, execute() {} }]); assert.throws(() => skills.registerExtensionSkill("com.test.readonly", manifest().skills[0], () => {}), { code: "EXTENSION_SKILL_COLLISION" }); });
test("installation, activation, invocation et résultat structuré", async () => { const fx = await ready(); const result = await fx.runtime.invoke(fx.rawManifest.id, fx.rawManifest.skills[0].id, { query: "Noon" }, { origin: "explicit_user_chat" }); assert.equal(result.ok, true); assert.equal(result.data.value, "Noon"); assert.equal(result.provenance.trust, "extension_data_untrusted"); });
test("une skill d'extension expose un alias compatible OpenAI sans perdre son identité canonique", async () => {
  const fx = await ready();
  const definition = fx.skills.getToolDefinitions().find((item) => item.description === "Lecture");
  assert.match(definition.name, /^[A-Za-z0-9_-]{1,64}$/);
  assert.notEqual(definition.name, fx.rawManifest.skills[0].id);
  assert.equal(fx.skills.getSkillByName(definition.name).definition.name, fx.rawManifest.skills[0].id);
  const result = await fx.skills.executeSkill(definition.name, { query: "alias" }, { origin: "explicit_user_chat" });
  assert.equal(result.data.value, "alias");
});
test("une installation sans revue reste désactivée", async () => { const rawManifest = manifest({ permissions: ["READ", "network.external"], allowedDomains: ["example.com"] }); const fx = fixture({ rawManifest }); fx.registry.discover({ manifest: rawManifest, module: fx.extension, provenance: "BUNDLED" }); fx.registry.install(rawManifest.id, { approvedPermissions: ["READ"] }); await assert.rejects(() => fx.registry.enable(rawManifest.id), { code: "EXTENSION_PERMISSION_REVIEW_REQUIRED" }); });
test("désactiver retire immédiatement les skills", async () => { const fx = await ready(); await fx.registry.disable(fx.rawManifest.id); assert.equal(fx.skills.getSkillByName(fx.rawManifest.skills[0].id), null); await assert.rejects(() => fx.runtime.invoke(fx.rawManifest.id, fx.rawManifest.skills[0].id, { query: "x" }), { code: "EXTENSION_DISABLED" }); });
test("désinstaller ne supprime pas silencieusement les données", async () => { const storage = createExtensionStorage(); const fx = await ready({ storage }); storage.namespace(fx.rawManifest.id).set("x", 1); const result = await fx.registry.uninstall(fx.rawManifest.id); assert.equal(result.dataRemoved, false); assert.equal(storage.hasData(fx.rawManifest.id), true); });
test("une provenance inconnue est mise en quarantaine", () => { const fx = fixture(); assert.equal(fx.registry.discover({ manifest: fx.rawManifest, module: fx.extension, provenance: "UNKNOWN" }).state, "QUARANTINED"); });
test("un feature flag OFF interdit l'activation", async () => { const skills = createSkillRegistry([]); const runtime = createExtensionRuntime({ securityPolicy: policy() }); const registry = createExtensionRegistry({ skillRegistry: skills, runtime, enabled: false }); runtime.bindRegistry(registry); const raw = manifest(); registry.discover({ manifest: raw, module: moduleFor(raw), provenance: "BUNDLED" }); registry.install(raw.id, { approvedPermissions: ["READ"] }); await assert.rejects(() => registry.enable(raw.id), { code: "EXTENSION_FEATURE_DISABLED" }); });
test("une extension locale exige le mode développeur explicite", () => { const denied = fixture(); assert.equal(denied.registry.discover({ manifest: denied.rawManifest, module: denied.extension, provenance: "LOCAL_DEVELOPMENT" }).state, "QUARANTINED"); const allowed = fixture({ developerMode: true }); assert.equal(allowed.registry.discover({ manifest: allowed.rawManifest, module: allowed.extension, provenance: "LOCAL_DEVELOPMENT" }).state, "DISCOVERED"); });
test("une mise à jour ne gagne pas silencieusement WRITE", async () => { const fx = await ready(); const nextManifest = manifest({ version: "2.0.0", permissions: ["READ", "WRITE"] }); const result = await fx.registry.update(fx.rawManifest.id, { manifest: nextManifest, module: moduleFor(nextManifest) }); assert.equal(result.updateBlocked, true); assert.deepEqual(result.addedPermissions, ["WRITE"]); });
test("la configuration est validée et la dernière valeur valide est conservée", () => { const rawManifest = manifest({ configSchema: object({ limit: { type: "integer" } }, ["limit"]) }); const fx = fixture({ rawManifest }); fx.registry.discover({ manifest: rawManifest, module: fx.extension, provenance: "BUNDLED" }); assert.equal(fx.registry.configure(rawManifest.id, { limit: 2 }).updated, true); assert.throws(() => fx.registry.configure(rawManifest.id, { limit: "beaucoup" }), { code: "EXTENSION_SCHEMA_VALIDATION_FAILED" }); assert.deepEqual(fx.registry.internal(rawManifest.id).config, { limit: 2 }); });
test("un plugin ne peut pas configurer un bypass de sécurité", () => { const rawManifest = manifest({ configSchema: object({ skipApproval: { type: "boolean" } }, ["skipApproval"]) }); const fx = fixture({ rawManifest }); fx.registry.discover({ manifest: rawManifest, module: fx.extension, provenance: "BUNDLED" }); assert.throws(() => fx.registry.configure(rawManifest.id, { skipApproval: true }), { code: "EXTENSION_SECURITY_CONFIG_DENIED" }); });
test("une permission non déclarée est bloquée", async () => { const rawManifest = manifest(); rawManifest.skills = [{ ...rawManifest.skills[0], permissionLevel: "WRITE" }]; const fx = await ready({ rawManifest, transactionalExecutor: async ({ operation }) => operation() }); await assert.rejects(() => fx.runtime.invoke(rawManifest.id, rawManifest.skills[0].id, { query: "x" }), { code: "EXTENSION_UNDECLARED_PERMISSION" }); });
test("une mutation ne contourne pas TransactionalExecutionEngine", async () => { const rawManifest = manifest({ permissions: ["WRITE"], skills: [{ ...manifest().skills[0], permissionLevel: "WRITE" }] }); const fx = await ready({ rawManifest }); await assert.rejects(() => fx.runtime.invoke(rawManifest.id, rawManifest.skills[0].id, { query: "x" }, { explicitOrder: true }), { code: "EXTENSION_TRANSACTIONAL_EXECUTION_REQUIRED" }); });
test("une approbation requise bloque le handler", async () => { let calls = 0; const fx = await ready({ outcome: "REQUIRE_APPROVAL", handler: async () => { calls += 1; return { value: "x" }; } }); const result = await fx.runtime.invoke(fx.rawManifest.id, fx.rawManifest.skills[0].id, { query: "x" }); assert.equal(result.status, "APPROVAL_REQUIRED"); assert.equal(calls, 0); });
test("un refus de policy ne produit aucun effet", async () => { let calls = 0; const fx = await ready({ outcome: "DENY", handler: async () => { calls += 1; return { value: "x" }; } }); await assert.rejects(() => fx.runtime.invoke(fx.rawManifest.id, fx.rawManifest.skills[0].id, { query: "x" }), { code: "EXTENSION_SECURITY_DENIED" }); assert.equal(calls, 0); });
test("une sortie invalide n'est jamais transmise", async () => { const fx = await ready({ handler: async () => ({ wrong: true }) }); await assert.rejects(() => fx.runtime.invoke(fx.rawManifest.id, fx.rawManifest.skills[0].id, { query: "x" }), { code: "EXTENSION_SCHEMA_VALIDATION_FAILED" }); });
test("un timeout interrompt l'invocation", async () => { const fx = await ready({ handler: () => new Promise(() => {}) }); await assert.rejects(() => fx.runtime.invoke(fx.rawManifest.id, fx.rawManifest.skills[0].id, { query: "x" }), { code: "EXTENSION_TIMEOUT" }); });
test("l'annulation est propagée", async () => { const fx = await ready({ handler: (_input, context) => new Promise((_resolve, reject) => context.abortSignal.addEventListener("abort", () => reject(Object.assign(new Error("stop"), { code: "EXTENSION_CANCELLED" })))) }); const controller = new AbortController(); const promise = fx.runtime.invoke(fx.rawManifest.id, fx.rawManifest.skills[0].id, { query: "x" }, { signal: controller.signal }); controller.abort(); await assert.rejects(() => promise, { code: "EXTENSION_CANCELLED" }); });
test("trois échecs health placent l'extension en quarantaine", async () => { const rawManifest = manifest(); const bad = defineExtension({ manifest: rawManifest, activate: () => ({ skills: { [rawManifest.skills[0].id]: async () => ({ value: "x" }) } }), healthCheck: async () => ({ ok: false }) }); const fx = fixture({ rawManifest }); fx.registry.discover({ manifest: rawManifest, module: bad, provenance: "BUNDLED" }); fx.registry.install(rawManifest.id, { approvedPermissions: ["READ"] }); await fx.registry.enable(rawManifest.id); await fx.registry.checkHealth(rawManifest.id); await fx.registry.checkHealth(rawManifest.id); await fx.registry.checkHealth(rawManifest.id); assert.equal(fx.registry.get(rawManifest.id).state, "QUARANTINED"); assert.equal(fx.skills.getSkillByName(rawManifest.skills[0].id), null); });
test("le stockage est isolé et limité", () => { const storage = createExtensionStorage({ quotaBytes: 30 }); storage.namespace("a").set("x", "ok"); assert.equal(storage.namespace("b").get("x"), undefined); assert.throws(() => storage.namespace("a").set("huge", "x".repeat(100)), { code: "EXTENSION_STORAGE_QUOTA" }); });
test("réseau non déclaré et domaine hors scope sont bloqués", async () => { const fx = await ready({ handler: (_input, context) => context.network.fetch("https://example.com") }); await assert.rejects(() => fx.runtime.invoke(fx.rawManifest.id, fx.rawManifest.skills[0].id, { query: "x" }), { code: "EXTENSION_PERMISSION_DENIED" }); });
test("la façade fichier respecte permission et racines réelles", async () => { const root = fs.mkdtempSync(path.join(os.tmpdir(), "noon-ext-files-")); const outside = fs.mkdtempSync(path.join(os.tmpdir(), "noon-ext-private-")); const insideFile = path.join(root, "visible.txt"); const outsideFile = path.join(outside, "secret.txt"); fs.writeFileSync(insideFile, "visible"); fs.writeFileSync(outsideFile, "secret"); const rawManifest = manifest({ permissions: ["READ", "filesystem.read"] }); const fx = await ready({ rawManifest, allowedRoots: [root], handler: ({ query }, context) => ({ value: context.filesystem.readText(query) }) }); assert.equal((await fx.runtime.invoke(rawManifest.id, rawManifest.skills[0].id, { query: insideFile })).data.value, "visible"); await assert.rejects(() => fx.runtime.invoke(rawManifest.id, rawManifest.skills[0].id, { query: outsideFile }), { code: "EXTENSION_FILESYSTEM_SCOPE_DENIED" }); });
test("le contexte ne fournit ni DB, ni mémoire, ni clé OpenAI, ni process.env", async () => { const fx = await ready({ handler: async (_input, context) => ({ value: String(Boolean(context.db || context.memory || context.openaiKey || context.env)) }) }); const result = await fx.runtime.invoke(fx.rawManifest.id, fx.rawManifest.skills[0].id, { query: "x" }); assert.equal(result.data.value, "false"); });
test("les événements d'observabilité ne contiennent pas les entrées ni sorties", async () => { const events = []; const skills = createSkillRegistry([]); const runtime = createExtensionRuntime({ securityPolicy: policy(), observability: (event, metadata) => events.push({ event, metadata }) }); const registry = createExtensionRegistry({ skillRegistry: skills, runtime, observability: (event, metadata) => events.push({ event, metadata }) }); runtime.bindRegistry(registry); const raw = manifest(); registry.discover({ manifest: raw, module: moduleFor(raw), provenance: "BUNDLED" }); registry.install(raw.id, { approvedPermissions: ["READ"] }); await registry.enable(raw.id); await runtime.invoke(raw.id, raw.skills[0].id, { query: "SECRET_INPUT" }); assert.equal(JSON.stringify(events).includes("SECRET_INPUT"), false); });
test("le loader refuse traversée et package symlink", () => { const root = fs.mkdtempSync(path.join(os.tmpdir(), "noon-ext-root-")); const outside = fs.mkdtempSync(path.join(os.tmpdir(), "noon-ext-out-")); fs.writeFileSync(path.join(outside, "index.js"), "module.exports = {};"); const linked = path.join(root, "linked"); fs.symlinkSync(outside, linked); const loader = createExtensionLoader({ roots: [root], developerMode: true }); assert.throws(() => loader.resolvePackage(outside), { code: "EXTENSION_PATH_OUTSIDE_ROOT" }); assert.throws(() => loader.resolvePackage(linked), { code: "EXTENSION_SYMLINK_PACKAGE_DENIED" }); });
test("trois crashes d'invocation mettent le plugin en quarantaine sans faire tomber le cœur", async () => { const fx = await ready({ handler: async () => { throw new Error("boom"); } }); for (let index = 0; index < 3; index += 1) await assert.rejects(() => fx.runtime.invoke(fx.rawManifest.id, fx.rawManifest.skills[0].id, { query: "x" })); assert.equal(fx.registry.get(fx.rawManifest.id).state, "QUARANTINED"); assert.equal(fx.skills.getSkillByName(fx.rawManifest.skills[0].id), null); });
