"use strict";

const test = require("node:test");
const assert = require("node:assert/strict");
const { createCapabilityRegistry, createLocalIntelligenceRuntime, createLocalModelAdapter, createOfflinePolicy } = require("../services/runtime");

function capability(capabilityId, overrides = {}) { return { capabilityId, provider: "noon", executionLocation: "LOCAL_DETERMINISTIC", availability: "AVAILABLE", qualityClass: "FULL", requiresNetwork: false, supportsLocalOnly: true, ...overrides }; }
function fixture({ preference = "BALANCED", localModel = null } = {}) {
  const values = { "runtime.executionPreference": preference, "offline.queueNetworkJobs": true };
  const config = { get: (key) => ({ value: values[key] }), set: (key, value) => { values[key] = value; } };
  const registry = createCapabilityRegistry([
    capability("LOCAL_FILES"), capability("LOCAL_SEARCH"), capability("LOCAL_MEMORY"), capability("LOCAL_ARTIFACT_BASIC"),
    capability("LOCAL_MODEL_TEXT", { executionLocation: "LOCAL_MODEL", availability: "UNKNOWN", qualityClass: "LIMITED", metadata: { alternativeFor: "REMOTE_REASONING" } }),
    capability("REMOTE_REASONING", { executionLocation: "REMOTE_MODEL", requiresNetwork: true, supportsLocalOnly: false, qualityClass: "FULL" }),
    capability("REMOTE_WEB_SEARCH", { executionLocation: "REMOTE_SERVICE", requiresNetwork: true, requiresRemoteData: true, supportsLocalOnly: false, qualityClass: "FULL" }),
    capability("REMOTE_GMAIL", { executionLocation: "REMOTE_SERVICE", requiresNetwork: true, requiresRemoteData: true, supportsLocalOnly: false, qualityClass: "FULL" }),
  ]);
  return { config, registry, runtime: createLocalIntelligenceRuntime({ registry, config, localModel: localModel || createLocalModelAdapter() }) };
}

test("online conserve le chemin distant normal", () => { const { runtime } = fixture(); const result = runtime.preflight({ requiredCapabilities: ["REMOTE_REASONING"] }); assert.equal(result.status, "AVAILABLE"); assert.equal(result.decisions[0].mode, "REMOTE_MODEL"); });
test("offline conserve fichiers, recherche, mémoire et artefacts locaux", () => { const { runtime } = fixture(); const snap = runtime.snapshot({ internetAvailable: false }); for (const id of ["LOCAL_FILES", "LOCAL_SEARCH", "LOCAL_MEMORY", "LOCAL_ARTIFACT_BASIC"]) assert.ok(snap.available.includes(id)); assert.ok(snap.unavailable.includes("REMOTE_WEB_SEARCH")); });
test("OpenAI indisponible reste distinct d'Internet indisponible", () => { const { runtime } = fixture(); const snap = runtime.snapshot({ providerAvailable: false }); assert.equal(snap.state, "PROVIDER_UNAVAILABLE"); assert.equal(snap.network.internet, "AVAILABLE"); assert.equal(snap.network.provider, "UNAVAILABLE"); });
test("une panne OpenAI coupe aussi la recherche Web dépendante du provider", () => { const { runtime } = fixture(); const snap = runtime.snapshot({ providerAvailable: false }); assert.ok(snap.unavailable.includes("REMOTE_REASONING")); assert.ok(snap.unavailable.includes("REMOTE_WEB_SEARCH")); assert.ok(snap.available.includes("REMOTE_GMAIL")); });
test("local-only interdit tout fallback distant", () => { const { runtime } = fixture({ preference: "LOCAL_ONLY" }); const result = runtime.preflight({ requiredCapabilities: ["REMOTE_WEB_SEARCH"], privacy: "LOCAL_ONLY" }); assert.equal(result.status, "UNAVAILABLE"); assert.equal(result.decisions[0].remoteForbidden, true); });
test("local-only persiste après un événement réseau", () => { const { runtime } = fixture({ preference: "LOCAL_ONLY" }); assert.equal(runtime.snapshot({ internetAvailable: true, providerAvailable: true }).state, "LOCAL_ONLY"); });
test("une panne réseau revient automatiquement online", () => { const { runtime } = fixture(); assert.equal(runtime.snapshot({ internetAvailable: false }).state, "OFFLINE"); assert.equal(runtime.snapshot({ internetAvailable: true }).state, "ONLINE"); });
test("sans modèle local le cœur déterministe reste utilisable", () => { const { runtime } = fixture(); const snap = runtime.snapshot({ internetAvailable: false }); assert.equal(snap.localModel.state, "NOT_CONFIGURED"); assert.ok(snap.available.includes("LOCAL_SEARCH")); });
test("un modèle local prêt est annoncé LIMITED, jamais équivalent à Sol", async () => { const adapter = createLocalModelAdapter({ provider: "TEST", model: "tiny", capabilities: ["LOCAL_MODEL_TEXT"], healthCheck: async () => ({ ready: true }), generate: async () => "résumé" }); await adapter.health(); const { runtime } = fixture({ localModel: adapter }); const result = runtime.preflight({ requiredCapabilities: ["REMOTE_REASONING"], context: { internetAvailable: false } }); assert.equal(result.status, "DEGRADED"); assert.equal(result.decisions[0].quality, "LIMITED"); });
test("un modèle local indisponible produit une limitation honnête", async () => { const adapter = createLocalModelAdapter({ provider: "TEST", model: "tiny", healthCheck: async () => ({ ready: false }) }); await adapter.health(); await assert.rejects(() => adapter.generate({ input: "x" }), { code: "LOCAL_MODEL_UNAVAILABLE" }); });
test("un modèle local n'obtient jamais l'autorité outil", async () => { const adapter = createLocalModelAdapter({ provider: "TEST", model: "tiny", healthCheck: async () => ({ ready: true }), generate: async () => "x" }); await adapter.health(); await assert.rejects(() => adapter.generate({ input: "x", toolAccess: true }), { code: "LOCAL_MODEL_TOOL_AUTHORITY_DENIED" }); });
test("une recherche actuelle n'utilise pas un faux cache local", () => { const { runtime } = fixture(); const result = runtime.preflight({ requiredCapabilities: ["REMOTE_WEB_SEARCH"], context: { internetAvailable: false }, qualityRequirement: "FULL" }); assert.equal(result.status, "UNAVAILABLE"); assert.equal(result.decisions[0].mode, "UNAVAILABLE"); });
test("un travail réseau n'est différé qu'avec intention explicite", () => { const { runtime } = fixture(); const absent = runtime.preflight({ requiredCapabilities: ["REMOTE_WEB_SEARCH"], context: { internetAvailable: false } }); const explicit = runtime.preflight({ requiredCapabilities: ["REMOTE_WEB_SEARCH"], context: { internetAvailable: false }, explicitQueueIntent: true }); assert.equal(absent.decisions[0].queueRemoteRetry, false); assert.equal(explicit.decisions[0].queueRemoteRetry, true); });
test("une action distante à haut risque n'est jamais mise en attente aveuglément", () => { const { runtime } = fixture(); const result = runtime.preflight({ requiredCapabilities: ["REMOTE_GMAIL"], context: { internetAvailable: false }, explicitQueueIntent: true, highRisk: true }); assert.equal(result.decisions[0].queueRemoteRetry, false); });
test("la policy préfère local quand la confidentialité l'exige", () => { const policy = createOfflinePolicy(); const local = capability("LOCAL_MODEL_TEXT", { executionLocation: "LOCAL_MODEL", availability: "AVAILABLE", qualityClass: "LIMITED" }); const remote = capability("REMOTE_REASONING", { executionLocation: "REMOTE_MODEL", requiresNetwork: true, supportsLocalOnly: false }); const result = policy.resolve({ requiredCapability: remote, alternatives: [local], privacy: "LOCAL_ONLY" }); assert.equal(result.capabilityId, "LOCAL_MODEL_TEXT"); assert.equal(result.remoteForbidden, true); });
test("changer explicitement de mode utilise la configuration persistante", () => { const { runtime } = fixture(); runtime.setPreference("LOCAL_ONLY", { origin: "user" }); assert.equal(runtime.snapshot().state, "LOCAL_ONLY"); runtime.setPreference("BALANCED", { origin: "user" }); assert.equal(runtime.snapshot().state, "ONLINE"); });
test("les événements d'observabilité ne contiennent aucun prompt", () => { const events = []; const { registry, config } = fixture(); const runtime = createLocalIntelligenceRuntime({ registry, config, observability: (event, data) => events.push([event, data]) }); runtime.preflight({ requiredCapabilities: ["LOCAL_SEARCH"] }); assert.equal(JSON.stringify(events).includes("contenu privé"), false); });
test("le health confirme l'absence d'autorité et de téléchargement", () => { const { runtime } = fixture(); assert.deepEqual({ executionAuthority: runtime.health().executionAuthority, modelDownloadAuthority: runtime.health().modelDownloadAuthority, securityBypass: runtime.health().securityBypass }, { executionAuthority: false, modelDownloadAuthority: false, securityBypass: false }); });
