"use strict";

const test = require("node:test");
const assert = require("node:assert/strict");
const fs = require("node:fs");
const os = require("node:os");
const path = require("node:path");
const { DatabaseSync } = require("node:sqlite");
const { createDeliveryRouter, createNotificationAttentionEngine, createNotificationPolicy, createNotificationStore, isQuietAt } = require("../services/notifications");

function clock(value = "2026-08-31T10:00:00.000Z") { let current = new Date(value); return { now: () => new Date(current), set: (next) => { current = new Date(next); } }; }
function request(overrides = {}) { return { source: "BACKGROUND_JOB", type: "COMPLETION", subjectRef: "job-1", payloadRef: "job-1", title: "Export terminé", summary: "Le rapport Qwenta est prêt.", genericSummary: "Le travail demandé est terminé.", interruptionLevel: "NORMAL", sensitivity: "NORMAL", allowedChannels: ["IN_APP", "MACOS_NOTIFICATION", "MOBILE_PUSH", "BADGE", "VOICE"], dedupeKey: "job:1:completed", replaceKey: "job-status:1", ...overrides }; }
function fixture({ at, mode = "ON", revalidator = null } = {}) {
  const time = clock(at); const deliveries = [];
  const router = createDeliveryRouter({ handlers: { IN_APP: async (record) => { deliveries.push(record); return { ok: true, acknowledged: true }; }, MACOS_NOTIFICATION: async (record) => { deliveries.push(record); return { ok: true }; }, MOBILE_PUSH: async (record) => { deliveries.push(record); return { ok: true, acknowledged: true }; }, VOICE: async (record) => { deliveries.push(record); return { ok: true }; }, BADGE: async (record) => { deliveries.push(record); return { ok: true }; } } });
  const engine = createNotificationAttentionEngine({ now: time.now, router, featureMode: mode, sourceRevalidator: revalidator });
  return { deliveries, engine, time };
}

test("une information passive reste in-app et badge", async () => { const { engine } = fixture(); const result = await engine.submit(request({ interruptionLevel: "PASSIVE" })); assert.deepEqual(result.plan.channels, ["IN_APP", "BADGE"]); });
test("job terminé devant la même conversation n'envoie pas de notification OS", async () => { const { engine } = fixture(); const result = await engine.submit(request({ conversationId: "c1" }), { appFocused: true, currentConversation: "c1" }); assert.deepEqual(result.plan.channels, ["IN_APP"]); });
test("job terminé utilisateur absent utilise in-app et macOS", async () => { const { engine } = fixture(); const result = await engine.submit(request(), { appFocused: false }); assert.deepEqual(result.plan.channels, ["IN_APP", "MACOS_NOTIFICATION"]); });
test("une demande explicite préviens-moi traverse le budget normal", async () => { const { engine } = fixture(); const recent = Array.from({ length: 9 }, (_, i) => ({ deliveredAt: `2026-08-31T09:${50 + i}:00Z` })); const result = await engine.submit(request({ userRequestedNotification: true }), { recentDeliveries: recent }); assert.ok(result.plan.channels.includes("MACOS_NOTIFICATION")); });
test("Focus diffère les notifications non critiques sans les perdre", async () => { const { engine } = fixture(); const result = await engine.submit(request(), { focusState: { active: true } }); assert.equal(result.plan.disposition, "DEFER"); assert.equal(result.request.state, "DEFERRED"); });
test("un événement urgent reste visible pendant Focus", async () => { const { engine } = fixture(); const result = await engine.submit(request({ interruptionLevel: "URGENT", importance: "CRITICAL" }), { focusState: { active: true } }); assert.equal(result.plan.disposition, "DELIVER"); });
test("quiet hours cross-midnight diffèrent le non critique", async () => { const { engine } = fixture({ at: "2026-08-31T21:30:00Z" }); const result = await engine.submit(request(), { quietHours: { enabled: true, startTime: "22:00", endTime: "07:00", timezone: "Europe/Paris" } }); assert.equal(result.plan.reason, "quiet_hours"); });
test("quiet hours fonctionnent de part et d'autre de minuit", () => { const q = { enabled: true, startTime: "22:00", endTime: "07:00", timezone: "Europe/Paris" }; assert.equal(isQuietAt(new Date("2026-08-31T21:30:00Z"), q), true); assert.equal(isQuietAt(new Date("2026-09-01T04:30:00Z"), q), true); assert.equal(isQuietAt(new Date("2026-09-01T10:00:00Z"), q), false); });
test("le calcul quiet hours reste stable autour du DST", () => { const q = { enabled: true, startTime: "22:00", endTime: "07:00", timezone: "Europe/Paris" }; assert.equal(isQuietAt(new Date("2026-10-25T05:30:00Z"), q), true); assert.equal(isQuietAt(new Date("2026-03-29T05:30:00Z"), q), false); });
test("une notification expirée pendant le silence n'est jamais délivrée", async () => { const { engine } = fixture(); const result = await engine.submit(request({ expiresAt: "2026-08-31T09:00:00Z" })); assert.equal(result.plan.disposition, "EXPIRE"); assert.equal(result.request.state, "EXPIRED"); });
test("protected sur écran verrouillé devient générique", async () => { const { engine } = fixture(); const result = await engine.submit(request({ sensitivity: "PROTECTED" }), { deviceLocked: true }); assert.ok(result.deliveries.every((item) => item.payload.body === "Le travail demandé est terminé.")); });
test("private sur écran verrouillé ne révèle pas le résumé", async () => { const { engine } = fixture(); const result = await engine.submit(request({ sensitivity: "PRIVATE", summary: "Diagnostic médical privé" }), { deviceLocked: true }); assert.equal(JSON.stringify(result.deliveries).includes("médical"), false); });
test("local_only ne produit jamais de mobile push", async () => { const { engine } = fixture(); const result = await engine.submit(request({ sensitivity: "LOCAL_ONLY", preferredChannels: ["MOBILE_PUSH", "IN_APP"] }), { activeDevice: { type: "mobile", scopes: ["NOTIFICATIONS"] } }); assert.equal(result.plan.channels.includes("MOBILE_PUSH"), false); });
test("derived local_only suit la même interdiction distante", async () => { const { engine } = fixture(); const result = await engine.submit(request({ derivedLocalOnly: true, preferredChannels: ["MOBILE_PUSH", "IN_APP"] }), { activeDevice: { type: "mobile", scopes: ["NOTIFICATIONS"] } }); assert.equal(result.plan.channels.includes("MOBILE_PUSH"), false); });
test("le même événement est livré une seule fois", async () => { const { deliveries, engine } = fixture(); await engine.submit(request()); const duplicate = await engine.submit(request({ attentionId: "other" })); assert.equal(duplicate.deduplicated, true); assert.equal(deliveries.length, 2); });
test("la déduplication permanente survit au redémarrage SQLite", async () => { const dir = fs.mkdtempSync(path.join(os.tmpdir(), "noon-attention-")); const db = new DatabaseSync(path.join(dir, "state.sqlite")); const time = clock(); const store1 = createNotificationStore({ database: db, now: time.now }); const e1 = createNotificationAttentionEngine({ store: store1, now: time.now, featureMode: "SHADOW" }); await e1.submit(request({ dedupeMode: "PERMANENT" })); const store2 = createNotificationStore({ database: db, now: time.now }); const e2 = createNotificationAttentionEngine({ store: store2, now: time.now, featureMode: "SHADOW" }); const result = await e2.submit(request({ attentionId: "new", dedupeMode: "PERMANENT" })); assert.equal(result.deduplicated, true); db.close(); });
test("un signal répété est borné par sa fenêtre de cooldown de livraison", async () => { const { engine, time } = fixture(); await engine.submit(request({ dedupeWindowMs: 1000 })); time.set("2026-08-31T10:00:00.500Z"); assert.equal((await engine.submit(request({ attentionId: "b", dedupeWindowMs: 1000 }))).deduplicated, true); time.set("2026-08-31T10:00:02Z"); assert.equal((await engine.submit(request({ attentionId: "c", dedupeWindowMs: 1000 }))).deduplicated, false); });
test("un état final remplace une progression antérieure", async () => { const { engine } = fixture(); await engine.submit(request({ type: "STATUS_CHANGE", dedupeKey: "run", replaceKey: "job-status:1" })); await engine.submit(request({ attentionId: "complete", dedupeKey: "complete", replaceKey: "job-status:1" })); assert.equal(engine.store.getRequest(engine.store.listRequests().find((item) => item.type === "STATUS_CHANGE").attentionId).state, "REPLACED"); });
test("DELIVERED ne devient jamais SEEN automatiquement", async () => { const { engine } = fixture(); const result = await engine.submit(request()); assert.ok(result.deliveries.every((item) => item.state === "DELIVERED")); assert.ok(result.deliveries.every((item) => item.interactedAt === null)); });
test("ouvrir explicitement un élément le marque SEEN", async () => { const { engine } = fixture(); const result = await engine.submit(request()); const interaction = await engine.interact({ deliveryId: result.deliveries[0].deliveryId, action: "OPEN" }); assert.equal(interaction.accepted, true); assert.equal(engine.store.getDelivery(result.deliveries[0].deliveryId).state, "SEEN"); });
test("une approval expirée ne produit aucun intent", async () => { const { engine, time } = fixture(); const result = await engine.submit(request({ source: "APPROVAL", type: "ACTION_REQUIRED", subjectRef: "approval-1", expiresAt: "2026-08-31T10:01:00Z", metadata: { exactActionRef: "approval-1", sourceFingerprint: "fp" } })); time.set("2026-08-31T10:02:00Z"); const action = await engine.interact({ deliveryId: result.deliveries[0].deliveryId, action: "APPROVE" }); assert.deepEqual(action, { accepted: false, reason: "expired" }); });
test("une source modifiée invalide l'ancienne action", async () => { const { engine } = fixture({ revalidator: async () => ({ valid: true, fingerprint: "new" }) }); const result = await engine.submit(request({ source: "APPROVAL", type: "ACTION_REQUIRED", metadata: { exactActionRef: "approval-1", sourceFingerprint: "old" } })); const action = await engine.interact({ deliveryId: result.deliveries[0].deliveryId, action: "APPROVE", sourceFingerprint: "old" }); assert.equal(action.reason, "source_changed"); });
test("une action notification reste trusted_ui sans bypass Security/Approval", async () => { const { engine } = fixture(); const result = await engine.submit(request({ source: "APPROVAL", type: "ACTION_REQUIRED", metadata: { exactActionRef: "approval-1" } })); const action = await engine.interact({ deliveryId: result.deliveries[0].deliveryId, action: "APPROVE" }); assert.equal(action.intent.origin, "trusted_ui"); assert.equal(action.intent.securityBypass, false); assert.equal(action.intent.approvalBypass, false); assert.equal(action.requiresSecurityEvaluation, true); });
test("le mobile exige le scope NOTIFICATIONS", async () => { const { engine } = fixture(); const denied = await engine.submit(request({ preferredChannels: ["MOBILE_PUSH", "IN_APP"] }), { activeDevice: { type: "mobile", scopes: [] } }); assert.equal(denied.plan.channels.includes("MOBILE_PUSH"), false); });
test("une session vocale explicite autorise une annonce générique", async () => { const { engine } = fixture(); const result = await engine.submit(request({ preferredChannels: ["VOICE", "IN_APP"] }), { voiceSessionActive: true, preferences: { voiceEnabled: true } }); assert.equal(result.plan.channels.includes("VOICE"), true); });
test("la voix ne lit jamais le contenu protected", async () => { const { engine } = fixture(); const result = await engine.submit(request({ sensitivity: "PROTECTED", preferredChannels: ["VOICE"] }), { voiceSessionActive: true, preferences: { voiceEnabled: true } }); assert.equal(result.deliveries[0].payload.body, "Le travail demandé est terminé."); });
test("sans session vocale Voice est retiré", async () => { const { engine } = fixture(); const result = await engine.submit(request({ preferredChannels: ["VOICE", "IN_APP"] }), { voiceSessionActive: false, preferences: { voiceEnabled: true } }); assert.deepEqual(result.plan.channels, ["IN_APP"]); });
test("le badge compte uniquement les actions non résolues", async () => { const { engine } = fixture(); await engine.submit(request({ userActionRequired: true })); await engine.submit(request({ attentionId: "info", dedupeKey: "info", replaceKey: null, userActionRequired: false })); assert.equal(engine.badgeCount(), 1); });
test("Shadow calcule sans aucune livraison réelle", async () => { const { deliveries, engine } = fixture({ mode: "SHADOW" }); const result = await engine.submit(request()); assert.equal(result.plan.disposition, "DELIVER"); assert.equal(deliveries.length, 0); });
test("une panne macOS conserve IN_APP", async () => { const router = createDeliveryRouter({ handlers: { IN_APP: async () => ({ ok: true }), MACOS_NOTIFICATION: async () => { throw Object.assign(new Error("down"), { code: "OS_DOWN" }); } } }); const engine = createNotificationAttentionEngine({ router, featureMode: "ON" }); const result = await engine.submit(request()); assert.ok(result.deliveries.some((item) => item.channel === "IN_APP" && item.state === "DELIVERED")); assert.ok(result.deliveries.some((item) => item.channel === "MACOS_NOTIFICATION" && item.state === "FAILED")); });
test("le budget d'attention convertit les interruptions suivantes en in-app/badge", async () => { const policy = createNotificationPolicy({ maxNonCriticalInterruptions: 1 }); const result = policy.evaluate(request(), { currentTime: "2026-08-31T10:00:00Z", recentDeliveries: [{ deliveredAt: "2026-08-31T09:59:00Z" }] }); assert.deepEqual(result.channels, ["IN_APP", "BADGE"]); });
test("aucune optimisation d'engagement n'existe dans le health", () => assert.equal(fixture().engine.health().engagementOptimization, false));
test("la télémétrie ne reçoit ni titre ni body privé", async () => { const events = []; const engine = createNotificationAttentionEngine({ featureMode: "SHADOW", observability: (name, data) => events.push([name, data]) }); await engine.submit(request({ title: "Client secret", summary: "Email privé" })); const serialized = JSON.stringify(events); assert.equal(serialized.includes("Client secret"), false); assert.equal(serialized.includes("Email privé"), false); });
test("les informations faibles compatibles sont regroupées dans un digest", () => { const { engine } = fixture(); const result = engine.coalesce([request({ subjectRef: "one", dedupeKey: "one", interruptionLevel: "PASSIVE", importance: "LOW" }), request({ subjectRef: "two", dedupeKey: "two", interruptionLevel: "PASSIVE", importance: "LOW" })]); assert.equal(result.requests.length, 1); assert.equal(result.coalescedCount, 1); assert.equal(result.requests[0].summary, "2 informations sont disponibles dans Noon."); });
test("un événement critique n'est jamais absorbé par le regroupement", () => { const { engine } = fixture(); const result = engine.coalesce([request({ subjectRef: "critical", importance: "CRITICAL", interruptionLevel: "URGENT" }), request({ subjectRef: "one", dedupeKey: "one", interruptionLevel: "PASSIVE", importance: "LOW" }), request({ subjectRef: "two", dedupeKey: "two", interruptionLevel: "PASSIVE", importance: "LOW" })]); assert.equal(result.requests.length, 2); assert.equal(result.requests.some((item) => item.importance === "CRITICAL"), true); });
