"use strict";
const assert = require("node:assert/strict");
const test = require("node:test");
const { CIRCUIT_STATES, FAILURE_CATEGORIES, HEALTH_STATES, READINESS_STATES, classifyFailure, createReliabilityEngine, redact } = require("../services/reliability/reliability-engine");
const { createTimeSlotService } = require("../services/scheduling/time-slot-service");

function fixture(options = {}) { let clock = Date.parse("2026-08-29T07:00:00Z"); const events = []; const engine = createReliabilityEngine({ now: () => clock, sleep: async () => {}, random: () => 0, observability: (event, metadata) => events.push({ event, metadata }), ...options }); return { engine, events, advance(ms) { clock += ms; } }; }
function register(engine, id, options = {}) { return engine.register({ componentId: id, type: "connector", criticality: "optional", capabilities: ["read"], ...options }); }

test("tous les composants vérifiés donnent un état global healthy", async () => { const f = fixture(); register(f.engine, "sqlite", { criticality: "critical", healthCheck: async () => ({ ok: true }) }); await f.engine.diagnose(); assert.equal(f.engine.report().overallState, HEALTH_STATES.HEALTHY); assert.equal(f.engine.report().readiness, READINESS_STATES.FULLY_READY); });
test("un connecteur optionnel indisponible garde le core en degraded ready", () => { const f = fixture(); register(f.engine, "sqlite", { criticality: "critical" }); register(f.engine, "gmail"); f.engine.recordSuccess("sqlite"); f.engine.recordFailure("gmail", Object.assign(new Error("unavailable"), { status: 503 })); assert.equal(f.engine.report().readiness, READINESS_STATES.DEGRADED_READY); });
test("NO_DATA est un succès et non une panne", async () => { const f = fixture(); register(f.engine, "gmail"); const result = await f.engine.execute("gmail", async () => []); assert.equal(result.outcome, "NO_DATA"); assert.equal(f.engine.snapshot("gmail").state, HEALTH_STATES.HEALTHY); });
test("auth expirée et permission refusée restent distinctes", () => { assert.equal(classifyFailure(Object.assign(new Error("token expired"), { status: 401 })).category, FAILURE_CATEGORIES.AUTH_REQUIRED); assert.equal(classifyFailure(Object.assign(new Error("forbidden"), { status: 403 })).category, FAILURE_CATEGORIES.PERMISSION_DENIED); });
test("rate limit, timeout et réseau sont classés précisément", () => { assert.equal(classifyFailure(Object.assign(new Error("quota"), { status: 429 })).category, FAILURE_CATEGORIES.RATE_LIMITED); assert.equal(classifyFailure(Object.assign(new Error("timeout"), { code: "ETIMEDOUT" })).category, FAILURE_CATEGORIES.TIMEOUT); assert.equal(classifyFailure(Object.assign(new Error("dns"), { code: "ENOTFOUND" })).category, FAILURE_CATEGORIES.NETWORK_ERROR); });
test("une lecture idempotente est retentée avec une limite", async () => { const f = fixture(); register(f.engine, "files", { maxRetries: 2 }); let calls = 0; const result = await f.engine.execute("files", async () => { calls += 1; if (calls < 3) throw Object.assign(new Error("timeout"), { code: "ETIMEDOUT" }); return ["ok"]; }); assert.equal(result.attempts, 3); assert.equal(calls, 3); });
test("une écriture externe n'est jamais retentée aveuglément", async () => { const f = fixture(); register(f.engine, "gmail"); let calls = 0; await assert.rejects(() => f.engine.execute("gmail", async () => { calls += 1; throw new Error("lost response"); }, { idempotent: false, destructive: true, unknownOutcome: true })); assert.equal(calls, 1); });
test("un outcome externe inconnu exige une vérification", () => { const result = classifyFailure(new Error("lost response"), { unknownOutcome: true }); assert.equal(result.category, FAILURE_CATEGORIES.UNKNOWN_OUTCOME); assert.equal(result.userActionRequired, true); });
test("le circuit s'ouvre après des échecs transitoires répétés puis récupère", async () => { const f = fixture(); register(f.engine, "gmail", { circuitThreshold: 2, circuitCooldownMs: 1000 }); f.engine.recordFailure("gmail", Object.assign(new Error("network"), { code: "ENOTFOUND" })); f.engine.recordFailure("gmail", Object.assign(new Error("network"), { code: "ENOTFOUND" })); assert.equal(f.engine.snapshot("gmail").circuitState, CIRCUIT_STATES.OPEN); await assert.rejects(() => f.engine.execute("gmail", async () => "x"), /suspendu/); f.advance(1001); await f.engine.execute("gmail", async () => "ok"); assert.equal(f.engine.snapshot("gmail").circuitState, CIRCUIT_STATES.CLOSED); });
test("le cache de health respecte son TTL", async () => { const f = fixture(); let checks = 0; register(f.engine, "sqlite", { ttlMs: 1000, healthCheck: async () => { checks += 1; } }); await f.engine.check("sqlite"); await f.engine.check("sqlite"); assert.equal(checks, 1); f.advance(1001); await f.engine.check("sqlite"); assert.equal(checks, 2); });
test("une panne SQLite critique rend Noon not ready", () => { const f = fixture(); register(f.engine, "sqlite", { criticality: "critical" }); f.engine.recordFailure("sqlite", new Error("database unavailable")); assert.equal(f.engine.report().readiness, READINESS_STATES.NOT_READY); });
test("une clé mémoire privée absente ne devient pas une mémoire vide", () => { const f = fixture(); register(f.engine, "private-memory", { criticality: "important" }); const error = f.engine.recordFailure("private-memory", Object.assign(new Error("missing key"), { code: "KEYSTORE_UNAVAILABLE" })); assert.equal(error.category, FAILURE_CATEGORIES.CONFIGURATION_ERROR); assert.equal(f.engine.snapshot("private-memory").state, HEALTH_STATES.MISCONFIGURED); });
test("racine absente et permission perdue restent distinctes", () => { assert.equal(classifyFailure(Object.assign(new Error("root unavailable"), { status: 503 })).category, FAILURE_CATEGORIES.SERVICE_UNAVAILABLE); assert.equal(classifyFailure(Object.assign(new Error("EACCES"), { code: "EACCES" })).category, FAILURE_CATEGORIES.PERMISSION_DENIED); });
test("source coverage distingue partiel, échec et résultat vide", () => { const f = fixture(); const coverage = f.engine.sourceCoverage(["file", "gmail"], [{ source: "file", status: "ok", results: [{ id: 1 }] }, { source: "gmail", status: "timeout" }]); assert.equal(coverage.state, "PARTIAL"); assert.deepEqual(coverage.succeeded, ["file"]); assert.equal(coverage.failed[0].componentId, "gmail"); const empty = f.engine.sourceCoverage(["gmail"], [{ source: "gmail", status: "ok", resultCount: 0, results: [] }]); assert.deepEqual(empty.noData, ["gmail"]); });
test("un renderer partiel dégrade seulement ses capacités", () => { const f = fixture(); register(f.engine, "artifacts", { capabilities: ["docx", "pdf"] }); f.engine.recordFailure("artifacts", new Error("PDF unavailable"), { partial: true, degradedCapabilities: ["pdf"] }); assert.equal(f.engine.snapshot("artifacts").state, HEALTH_STATES.DEGRADED); assert.deepEqual(f.engine.snapshot("artifacts").degradedCapabilities, ["pdf"]); });
test("une panne TTS optionnelle laisse le chat disponible", () => { const f = fixture(); register(f.engine, "text-chat", { criticality: "critical" }); register(f.engine, "tts"); f.engine.recordSuccess("text-chat"); f.engine.recordFailure("tts", new Error("unavailable")); assert.equal(f.engine.report().readiness, READINESS_STATES.DEGRADED_READY); });
test("la protection budget n'est pas classée comme panne modèle", () => { const failure = classifyFailure(Object.assign(new Error("Budget protection"), { code: "BUDGET_BLOCKED" })); assert.notEqual(failure.category, FAILURE_CATEGORIES.SERVICE_UNAVAILABLE); });
test("un cache stale est détecté et une réparation sûre peut l'invalider", async () => { const f = fixture(); let repaired = false; register(f.engine, "context-cache", { safeRepair: async () => { repaired = true; return "cleared"; } }); f.engine.recordFailure("context-cache", new Error("stale fingerprint"), { stale: true }); assert.equal(f.engine.snapshot("context-cache").state, HEALTH_STATES.STALE); assert.equal((await f.engine.selfHeal("context-cache")).repaired, true); assert.equal(repaired, true); });
test("aucune réparation dangereuse n'est inventée", async () => { const f = fixture(); register(f.engine, "sqlite", { criticality: "critical" }); assert.deepEqual(await f.engine.selfHeal("sqlite"), { repaired: false, reason: "NO_SAFE_REPAIR" }); });
test("un démarrage ne vérifie activement que le core", async () => { const f = fixture(); let optionalChecks = 0; register(f.engine, "sqlite", { criticality: "critical", healthCheck: async () => {} }); register(f.engine, "gmail", { healthCheck: async () => { optionalChecks += 1; } }); await f.engine.diagnose(); assert.equal(optionalChecks, 0); assert.equal(f.engine.report().readiness, READINESS_STATES.CORE_READY); });
test("les diagnostics et fingerprints sont redacted", () => { const f = fixture(); register(f.engine, "gmail"); const error = f.engine.recordFailure("gmail", new Error("sk-secret123 arnaud@example.com /Users/arnaud/private.txt Authorization Bearer abc")); const output = JSON.stringify({ report: f.engine.report({ includeHistory: true }), error }); assert.equal(output.includes("secret123"), false); assert.equal(output.includes("arnaud@example.com"), false); assert.equal(output.includes("/Users/arnaud"), false); assert.equal(redact("api_key=abcdef"), "secret=[REDACTED]"); });
test("le diagnostic explique l'impact sans laisser le modèle deviner", () => { const f = fixture(); register(f.engine, "gmail", { impact: "Les emails ne sont pas inclus." }); f.engine.recordFailure("gmail", Object.assign(new Error("token expired"), { status: 401 })); const explanation = f.engine.explain(["gmail"]); assert.match(explanation.text, /emails ne sont pas inclus/); assert.equal(explanation.issues[0].reasonCode, FAILURE_CATEGORIES.AUTH_REQUIRED); });
test("les changements matériels et récupérations sont dédupliqués", () => { const f = fixture(); register(f.engine, "gmail"); f.engine.recordFailure("gmail", Object.assign(new Error("token expired"), { status: 401 })); assert.equal(f.engine.notifyMaterialChanges().length, 1); assert.equal(f.engine.notifyMaterialChanges().length, 0); f.engine.recordSuccess("gmail"); assert.equal(f.engine.notifyMaterialChanges().length, 1); });
test("l'observabilité en panne ne casse pas le moteur", () => { const f = fixture({ observability: () => { throw new Error("metrics down"); } }); register(f.engine, "sqlite"); assert.doesNotThrow(() => f.engine.recordSuccess("sqlite")); });
test("l'historique de diagnostic est borné et sans messages bruts", () => { const f = fixture({ historyLimit: 2 }); register(f.engine, "gmail"); f.engine.recordFailure("gmail", new Error("private body")); f.engine.recordSuccess("gmail"); f.engine.recordFailure("gmail", new Error("another private body")); assert.equal(f.engine.history().length, 2); assert.equal(JSON.stringify(f.engine.history()).includes("private body"), false); });
test("un agenda non connecté ne produit jamais de faux créneau libre", async () => { const service = createTimeSlotService({ connected: false }); await assert.rejects(service.suggest({ durationMinutes: 45 }), (error) => error.code === "CALENDAR_AUTH_REQUIRED" && /n.a pas pu être vérifié/i.test(error.message)); });
