"use strict";

const assert = require("node:assert/strict");
const fs = require("node:fs");
const os = require("node:os");
const path = require("node:path");
const test = require("node:test");
const { createTransactionalExecutionEngine, ExecutionError } = require("../services/execution/transactional-execution-engine");
const { createReliabilityEngine } = require("../services/reliability/reliability-engine");
const { createPersonalDatabase } = require("../services/persistence/database");
const { createTransactionalExecutionRepository } = require("../services/persistence/repositories/transactional-execution-repository");

function memoryRepository() {
  const executions = new Map(); const steps = new Map(); let failWrites = false;
  return {
    fail() { failWrites = true; },
    saveExecution(record) { if (failWrites) throw new Error("disk full"); executions.set(record.execution_id, structuredClone(record)); return record; },
    saveStep(record) { if (failWrites) throw new Error("disk full"); steps.set(`${record.execution_id}:${record.step_id}`, structuredClone(record)); return record; },
    getExecution(id) { const value = executions.get(id); return value ? structuredClone(value) : null; },
    getSteps(id) { return [...steps.values()].filter((item) => item.execution_id === id).map((item) => structuredClone(item)); },
    findStepByIdempotencyKey(key) { const value = [...steps.values()].find((item) => item.idempotency_key === key); return value ? structuredClone(value) : null; },
    listRecoverable() { return [...executions.values()].filter((item) => ["RUNNING", "VERIFYING", "COMPENSATING"].includes(item.state)).map((item) => structuredClone(item)); },
    transaction(callback) { return callback(); },
  };
}

const schemas = {
  read_file: { required: ["path"], properties: { path: { type: "string" } } },
  write_file: { required: ["path", "content"], properties: { path: { type: "string" }, content: { type: "string" } } },
  calendar_create: { required: ["title"], properties: { title: { type: "string" } } },
  send_email: { required: ["to"], properties: { to: { type: "string" }, body: { type: "string" } } },
  git_commit: { required: ["message"], properties: { message: { type: "string" } } },
  git_push: { required: [], properties: {} },
};
function registry() {
  return { getSkillByName(name) { const schema = schemas[name]; return schema ? { definition: { name, parameters: { type: "object", additionalProperties: false, ...schema } } } : null; } };
}
function fixture(options = {}) {
  const repository = options.repository || memoryRepository(); const events = [];
  const engine = createTransactionalExecutionEngine({ repository, skillRegistry: registry(), reliabilityEngine: options.reliabilityEngine, observability: (event, metadata) => events.push({ event, metadata }), maxSteps: options.maxSteps || 20 });
  return { engine, repository, events };
}
function request(id, overrides = {}) {
  return { executionId: id, profileScope: "arnaud", workspaceId: "workspace-a", revalidate: () => ({ outcome: "ALLOW" }), executeStep: async () => ({ id: `${id}-result` }), step: { stepId: "step-1", skillId: "read_file", args: { path: "/tmp/test.txt" }, actionClass: "READ", verificationLevel: "NONE" }, ...overrides };
}

test("une lecture simple est planifiée, exécutée et réussie", async () => { const f = fixture(); const result = await f.engine.executeSingleStep(request("read")); assert.equal(result.status, "SUCCEEDED"); assert.deepEqual(result.succeededSteps, ["step-1"]); });
test("un fichier est créé une seule fois et vérifié", async () => { const f = fixture(); let writes = 0; const input = request("file-create", { step: { stepId: "write", skillId: "write_file", args: { path: "/tmp/a", content: "x" }, actionClass: "WRITE", verificationLevel: "STRONG", verification: () => ({ verified: true, reasonCode: "HASH_MATCH" }) }, executeStep: () => { writes += 1; return { id: "file-1" }; } }); const result = await f.engine.executeSingleStep(input); assert.equal(result.status, "SUCCEEDED"); assert.equal(writes, 1); assert.equal(f.engine.get("file-create").steps[0].verification_state, "HASH_MATCH"); });
test("un double appel simultané de la même execution ne produit qu'un effet", async () => { const f = fixture(); let writes = 0; const input = request("double", { step: { stepId: "write", skillId: "write_file", args: { path: "/tmp/a", content: "x" }, actionClass: "WRITE" }, executeStep: async () => { writes += 1; await new Promise((resolve) => setImmediate(resolve)); return { id: "file" }; } }); await Promise.all([f.engine.executeSingleStep(input), f.engine.executeSingleStep(input)]); assert.equal(writes, 1); });
test("un appel terminal identique est supprimé comme doublon", async () => { const f = fixture(); let calls = 0; const input = request("terminal", { executeStep: () => { calls += 1; return { id: "x" }; } }); await f.engine.executeSingleStep(input); const again = await f.engine.executeSingleStep(input); assert.equal(again.duplicate, true); assert.equal(calls, 1); });
test("une clé d'idempotence stable évite un second effet dans une autre reprise", async () => { const f = fixture(); let calls = 0; const make = (id) => request(id, { step: { stepId: "write", skillId: "write_file", args: { path: "/tmp/a", content: "x" }, actionClass: "WRITE", idempotencyKey: "stable-write" }, executeStep: () => { calls += 1; return { id: "file" }; } }); await f.engine.executeSingleStep(make("first")); const second = await f.engine.executeSingleStep(make("retry")); assert.equal(second.status, "SUCCEEDED"); assert.equal(calls, 1); });
test("un overwrite stale est bloqué avant le handler", async () => { const f = fixture(); let calls = 0; const result = await f.engine.executeSingleStep(request("stale", { step: { stepId: "write", skillId: "write_file", args: { path: "/tmp/a", content: "x" }, actionClass: "WRITE" }, checkPreconditions: () => ({ valid: false }), executeStep: () => { calls += 1; } })); assert.equal(result.status, "FAILED"); assert.equal(calls, 0); assert.equal(f.engine.get("stale").steps[0].reason_code, "STALE_PRECONDITION"); });
test("une policy modifiée bloque le side effect just-in-time", async () => { const f = fixture(); let calls = 0; const result = await f.engine.executeSingleStep(request("policy", { revalidate: () => ({ outcome: "DENY" }), executeStep: () => { calls += 1; } })); assert.equal(result.status, "FAILED"); assert.equal(calls, 0); });
test("une approbation absente place le plan en attente", async () => { const f = fixture(); const result = await f.engine.executeSingleStep(request("approval", { approvalRequired: true })); assert.equal(result.status, "AWAITING_APPROVAL"); });
test("un timeout Calendar au résultat inconnu n'est jamais rejoué", async () => { const f = fixture(); let calls = 0; const result = await f.engine.executeSingleStep(request("calendar-unknown", { step: { stepId: "event", skillId: "calendar_create", args: { title: "Focus" }, actionClass: "WRITE" }, executeStep: () => { calls += 1; throw Object.assign(new Error("lost response"), { code: "UNKNOWN_OUTCOME" }); } })); assert.equal(result.status, "UNKNOWN_OUTCOME"); assert.equal(calls, 1); assert.deepEqual(result.pendingRecovery, ["event"]); });
test("un envoi email incertain reste UNKNOWN_OUTCOME", async () => { const f = fixture(); const result = await f.engine.executeSingleStep(request("mail-unknown", { step: { stepId: "send", skillId: "send_email", args: { to: "a@example.test" }, actionClass: "EXECUTE" }, executeStep: () => { throw Object.assign(new Error("response lost"), { code: "UNKNOWN_OUTCOME" }); } })); assert.equal(result.status, "UNKNOWN_OUTCOME"); });
test("un email avec provider ID obtient un succès vérifié", async () => { const f = fixture(); const result = await f.engine.executeSingleStep(request("mail-ok", { step: { stepId: "send", skillId: "send_email", args: { to: "a@example.test" }, actionClass: "EXECUTE", verificationLevel: "STRONG", verification: (envelope) => ({ verified: envelope.result.messageId === "m-1", reasonCode: "SENT_LOOKUP" }) }, executeStep: () => ({ messageId: "m-1" }) })); assert.equal(result.status, "SUCCEEDED"); });
test("une dépendance attend l'étape précédente", async () => { const f = fixture(); const order = []; const plan = f.engine.createPlan({ executionId: "deps", steps: [{ stepId: "a", skillId: "write_file", args: { path: "/tmp/a", content: "x" }, actionClass: "WRITE" }, { stepId: "b", skillId: "send_email", args: { to: "a@example.test" }, actionClass: "EXECUTE", dependencies: ["a"] }] }); const result = await f.engine.execute({ plan, profileScope: "arnaud", workspaceId: "workspace-a", revalidate: () => ({ outcome: "ALLOW" }), executeStep: (step) => { order.push(step.stepId); return { id: step.stepId }; } }); assert.equal(result.status, "SUCCEEDED"); assert.deepEqual(order, ["a", "b"]); });
test("une dépendance échouée provoque SKIPPED_DEPENDENCY", async () => { const f = fixture(); const plan = f.engine.createPlan({ executionId: "deps-fail", failurePolicy: "RETURN_PARTIAL", steps: [{ stepId: "a", skillId: "write_file", args: { path: "/tmp/a", content: "x" }, actionClass: "WRITE" }, { stepId: "b", skillId: "send_email", args: { to: "a@example.test" }, actionClass: "EXECUTE", dependencies: ["a"] }] }); const result = await f.engine.execute({ plan, profileScope: "arnaud", workspaceId: "workspace-a", revalidate: () => ({ outcome: "ALLOW" }), executeStep: (step) => { if (step.stepId === "a") throw new Error("fail"); return {}; } }); assert.equal(result.status, "FAILED"); assert.deepEqual(result.skippedSteps, ["b"]); });
test("un cycle est refusé avant toute exécution", () => { const f = fixture(); assert.throws(() => f.engine.createPlan({ executionId: "cycle", steps: [{ stepId: "a", skillId: "read_file", args: { path: "/tmp/a" }, dependencies: ["b"] }, { stepId: "b", skillId: "read_file", args: { path: "/tmp/b" }, dependencies: ["a"] }] }), (error) => error.code === "PLAN_CYCLE"); });
test("un skill inconnu est refusé avant toute exécution", () => { const f = fixture(); assert.throws(() => f.engine.createPlan({ executionId: "unknown", step: { skillId: "missing", args: {} } }), (error) => error.code === "UNKNOWN_SKILL"); });
test("des arguments invalides sont refusés avant tout effet", () => { const f = fixture(); assert.throws(() => f.engine.createPlan({ executionId: "args", step: { skillId: "send_email", args: { other: true } } }), (error) => error.code === "INVALID_ARGS"); });
test("un workflow multi-step rend un résultat PARTIAL transparent", async () => { const f = fixture(); const plan = f.engine.createPlan({ executionId: "partial", failurePolicy: "RETURN_PARTIAL", steps: [{ stepId: "pdf", skillId: "write_file", args: { path: "/tmp/a", content: "x" }, actionClass: "WRITE" }, { stepId: "mail", skillId: "send_email", args: { to: "a@example.test" }, actionClass: "EXECUTE" }] }); const result = await f.engine.execute({ plan, profileScope: "arnaud", workspaceId: "workspace-a", revalidate: () => ({ outcome: "ALLOW" }), executeStep: (step) => { if (step.stepId === "mail") throw new Error("down"); return { id: "pdf" }; } }); assert.equal(result.status, "PARTIAL"); assert.deepEqual(result.succeededSteps, ["pdf"]); assert.deepEqual(result.failedSteps, ["mail"]); });
test("une compensation locale sûre est exécutée", async () => { const f = fixture(); let compensated = 0; const plan = f.engine.createPlan({ executionId: "compensate", failurePolicy: "COMPENSATE", steps: [{ stepId: "temp", skillId: "write_file", args: { path: "/tmp/a", content: "x" }, actionClass: "WRITE", compensation: { autoSafe: true, targetCreatedByExecution: true, execute: () => { compensated += 1; } } }, { stepId: "mail", skillId: "send_email", args: { to: "a@example.test" }, actionClass: "EXECUTE" }] }); const result = await f.engine.execute({ plan, profileScope: "arnaud", workspaceId: "workspace-a", revalidate: () => ({ outcome: "ALLOW" }), executeStep: (step) => { if (step.stepId === "mail") throw new Error("fail"); return { id: "temp" }; } }); assert.equal(result.status, "COMPENSATED"); assert.equal(compensated, 1); });
test("une compensation qui échoue reste visible en récupération", async () => { const f = fixture(); const plan = f.engine.createPlan({ executionId: "comp-fail", failurePolicy: "COMPENSATE", steps: [{ stepId: "temp", skillId: "write_file", args: { path: "/tmp/a", content: "x" }, actionClass: "WRITE", compensation: { autoSafe: true, targetCreatedByExecution: true, execute: () => { throw new Error("fail"); } } }, { stepId: "mail", skillId: "send_email", args: { to: "a@example.test" }, actionClass: "EXECUTE" }] }); const result = await f.engine.execute({ plan, profileScope: "arnaud", workspaceId: "workspace-a", revalidate: () => ({ outcome: "ALLOW" }), executeStep: (step) => { if (step.stepId === "mail") throw new Error("fail"); return { id: "temp" }; } }); assert.equal(result.status, "PARTIAL"); assert.deepEqual(result.pendingRecovery, ["temp"]); });
test("une vérification métier négative empêche SUCCEEDED", async () => { const f = fixture(); const result = await f.engine.executeSingleStep(request("verify-fail", { step: { stepId: "write", skillId: "write_file", args: { path: "/tmp/a", content: "x" }, actionClass: "WRITE", verificationLevel: "STRONG", verification: () => ({ verified: false, reasonCode: "HASH_MISMATCH" }) } })); assert.equal(result.status, "FAILED"); });
test("une vérification impossible après application devient UNKNOWN_OUTCOME", async () => { const f = fixture(); const result = await f.engine.executeSingleStep(request("verify-unknown", { step: { stepId: "push", skillId: "git_push", args: {}, actionClass: "EXECUTE", verificationLevel: "STRONG", verification: () => { throw Object.assign(new Error("remote unavailable"), { code: "REMOTE_LOOKUP_FAILED" }); } } })); assert.equal(result.status, "UNKNOWN_OUTCOME"); });
test("un journal indisponible bloque une mutation avant le side effect", async () => { const repository = memoryRepository(); repository.fail(); const f = fixture({ repository }); let calls = 0; await assert.rejects(() => f.engine.executeSingleStep(request("journal-fail", { executeStep: () => { calls += 1; } })), (error) => error.code === "EXECUTION_JOURNAL_UNAVAILABLE"); assert.equal(calls, 0); });
test("le redémarrage marque les exécutions actives INTERRUPTED sans replay", () => { const repository = memoryRepository(); const stamp = new Date().toISOString(); repository.saveExecution({ execution_id: "crash", state: "RUNNING", profile_scope: "arnaud", updated_at: stamp }); repository.saveStep({ execution_id: "crash", step_id: "send", state: "RUNNING", updated_at: stamp }); const f = fixture({ repository }); assert.deepEqual(f.engine.recoverInterrupted(), ["crash"]); assert.equal(f.engine.get("crash").execution.state, "INTERRUPTED"); assert.equal(f.engine.get("crash").steps[0].state, "UNKNOWN_OUTCOME"); });
test("une reprise sous un autre profil ou workspace est refusée", async () => { const f = fixture(); const input = request("scope"); await f.engine.executeSingleStep(input); await assert.rejects(() => f.engine.executeSingleStep({ ...input, profileScope: "alexandra" }), (error) => error.code === "EXECUTION_SCOPE_MISMATCH"); });
test("un plan approuvé ne peut pas être réécrit silencieusement", async () => { const f = fixture(); const input = request("immutable"); await f.engine.executeSingleStep(input); const changed = request("immutable", { step: { stepId: "step-1", skillId: "read_file", args: { path: "/tmp/other.txt" }, actionClass: "READ" } }); await assert.rejects(() => f.engine.executeSingleStep(changed), (error) => error.code === "EXECUTION_PLAN_CHANGED"); });
test("une annulation pendant une étape n'invente pas de rollback et stoppe la suivante", async () => { const f = fixture(); let release; const gate = new Promise((resolve) => { release = resolve; }); const plan = f.engine.createPlan({ executionId: "cancel", failurePolicy: "RETURN_PARTIAL", steps: [{ stepId: "first", skillId: "read_file", args: { path: "/tmp/a" }, actionClass: "READ" }, { stepId: "second", skillId: "read_file", args: { path: "/tmp/b" }, actionClass: "READ" }] }); const pending = f.engine.execute({ plan, profileScope: "arnaud", workspaceId: "workspace-a", revalidate: () => ({ outcome: "ALLOW" }), executeStep: async (step) => { if (step.stepId === "first") await gate; return { id: step.stepId }; } }); await new Promise((resolve) => setImmediate(resolve)); assert.equal(f.engine.cancel("cancel").cancelled, true); release(); const result = await pending; assert.equal(result.status, "PARTIAL"); assert.deepEqual(result.succeededSteps, ["first"]); assert.deepEqual(result.skippedSteps, ["second"]); });
test("les lectures idempotentes utilisent les retries bornés de Reliability", async () => { const reliability = createReliabilityEngine({ sleep: async () => {}, random: () => 0 }); reliability.register({ componentId: "filesystem", maxRetries: 2 }); const f = fixture({ reliabilityEngine: reliability }); let calls = 0; const result = await f.engine.executeSingleStep(request("retry-read", { componentId: "filesystem", executeStep: () => { calls += 1; if (calls < 2) throw Object.assign(new Error("timeout"), { code: "ETIMEDOUT" }); return { id: "ok" }; } })); assert.equal(result.status, "SUCCEEDED"); assert.equal(calls, 2); });
test("une écriture non idempotente n'est pas retentée aveuglément", async () => { const reliability = createReliabilityEngine({ sleep: async () => {} }); reliability.register({ componentId: "gmail", maxRetries: 3 }); const f = fixture({ reliabilityEngine: reliability }); let calls = 0; const result = await f.engine.executeSingleStep(request("unsafe-retry", { componentId: "gmail", step: { stepId: "send", skillId: "send_email", args: { to: "a@example.test" }, actionClass: "EXECUTE" }, executeStep: () => { calls += 1; throw new Error("lost response"); } })); assert.equal(result.status, "UNKNOWN_OUTCOME"); assert.equal(calls, 1); });
test("les traces ne contiennent ni arguments, ni email, ni contenu", async () => { const f = fixture(); await f.engine.executeSingleStep(request("privacy", { step: { stepId: "send", skillId: "send_email", args: { to: "private@example.test", body: "SECRET_BODY" }, actionClass: "EXECUTE" } })); const serialized = JSON.stringify(f.events); assert.doesNotMatch(serialized, /private@example|SECRET_BODY/); assert.ok(f.events.some((item) => item.event === "execution_completed")); });
test("le journal SQLite conserve états et idempotency key après réouverture", async () => { const directory = fs.mkdtempSync(path.join(os.tmpdir(), "noon-transaction-")); const file = path.join(directory, "noon.sqlite"); let database = createPersonalDatabase(file); let repository = createTransactionalExecutionRepository(database); let engine = createTransactionalExecutionEngine({ repository, skillRegistry: registry() }); await engine.executeSingleStep(request("persist", { step: { stepId: "commit", skillId: "git_commit", args: { message: "test" }, actionClass: "WRITE", idempotencyKey: "commit-stable" } })); database.close(); database = createPersonalDatabase(file); repository = createTransactionalExecutionRepository(database); engine = createTransactionalExecutionEngine({ repository, skillRegistry: registry() }); assert.equal(engine.get("persist").execution.state, "SUCCEEDED"); assert.equal(engine.get("persist").steps[0].idempotency_key, "commit-stable"); database.close(); });
test("un plan trop long est refusé", () => { const f = fixture({ maxSteps: 1 }); assert.throws(() => f.engine.createPlan({ executionId: "long", steps: [{ stepId: "a", skillId: "read_file", args: { path: "/tmp/a" } }, { stepId: "b", skillId: "read_file", args: { path: "/tmp/b" } }] }), (error) => error instanceof ExecutionError && error.code === "TOO_MANY_STEPS"); });
