"use strict";

const SYNC_PROTOCOL_VERSION = 1;
const SYNC_CLASSIFICATIONS = Object.freeze(["SYNC_ALLOWED", "SYNC_METADATA_ONLY", "SYNC_ON_REQUEST", "LOCAL_ONLY", "SYNC_FORBIDDEN"]);
const DEVICE_TYPES = Object.freeze(["MAC_PRIMARY", "MAC_SECONDARY", "IPHONE", "IPAD"]);
const DEVICE_STATUSES = Object.freeze(["PENDING", "ACTIVE", "SUSPENDED", "REVOKED", "STALE"]);
const DEVICE_SCOPES = Object.freeze(["CONVERSATIONS", "WORKSPACES", "JOB_STATUS", "NOTIFICATIONS", "ARTIFACT_METADATA", "ARTIFACT_DOWNLOAD", "REMOTE_REQUESTS", "REMOTE_TEXT", "REMOTE_JOBS", "REMOTE_MEDIA", "REMOTE_APPROVALS", "REMOTE_VOICE"]);
const SYNC_OPERATIONS = Object.freeze(["UPSERT", "DELETE", "TOMBSTONE"]);
const OUTBOX_STATES = Object.freeze(["PENDING", "SENDING", "ACKNOWLEDGED", "FAILED", "PAUSED"]);
const CONFLICT_STATES = Object.freeze(["AUTO_RESOLVED", "NEEDS_USER", "RESOLVED"]);
const EXECUTION_NODES = Object.freeze(["MAC_PRIMARY", "LOCAL_DEVICE", "ANY_AUTHORIZED_NODE"]);
const PROTOCOL_COMPATIBILITY = Object.freeze({ COMPATIBLE: "COMPATIBLE", LIMITED: "LIMITED", UPGRADE_REQUIRED: "UPGRADE_REQUIRED" });

function negotiateProtocol(remoteVersion) {
  const version = Number(remoteVersion);
  if (version === SYNC_PROTOCOL_VERSION) return { status: PROTOCOL_COMPATIBILITY.COMPATIBLE, readOnly: false };
  if (version === SYNC_PROTOCOL_VERSION - 1) return { status: PROTOCOL_COMPATIBILITY.LIMITED, readOnly: true };
  return { status: PROTOCOL_COMPATIBILITY.UPGRADE_REQUIRED, readOnly: true };
}

module.exports = { CONFLICT_STATES, DEVICE_SCOPES, DEVICE_STATUSES, DEVICE_TYPES, EXECUTION_NODES, OUTBOX_STATES, PROTOCOL_COMPATIBILITY, SYNC_CLASSIFICATIONS, SYNC_OPERATIONS, SYNC_PROTOCOL_VERSION, negotiateProtocol };
